version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "ECS-Cluster-Scaledown"
s3_bucket = "<sam-deploy-bucket>"
s3_prefix = "ecs-cluster-scaledown"
region = "<region>"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
  "appName=ECS-Cluster-Scaledown"
]
